# 기본 정보 설정
encoding: utf-8
title: ""
# 반드시 아래 url을 사용자님의 Vercel 주소로 설정해야 메뉴가 작동합니다.
url: "https://gucc-insight.vercel.app"
baseurl: "" 
minimal_mistakes_skin: "air" #화이트 스킨 적용

masthead_title: "GAME GENERATION" # 로고 텍스트
# 만약 로고 이미지가 있다면 아래 추가
# logo: "/assets/images/logo.png"

search: true
remote_theme: "mmistakes/minimal-mistakes"

# 빌드 및 게시글 설정
paginate: 10
paginate_path: /page:num/
markdown: kramdown
excerpt_separator: "" # 요약글 구분자

# 기본 레이아웃 설정
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      entries_layout: grid
      classes: wide

# 아카이브 페이지 설정 (404 방지)
category_archive:
  type: grid
  path: /categories/
tag_archive:
  type: grid
  path: /tags/

# 필수 플러그인
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
  - jekyll-remote-theme
  - jekyll-include-cache

# 빌드 제외 목록
exclude:
  - admin/cms.js
  - admin/config.yml_backup
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules
  - .vercel
