backend:
  name: github
  repo: "guccehchoi-commits/gucc_insight" # 예: "gucc/gucc-insight" 형식으로 수정 필요
  branch: master

media_folder: "images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "블로그 포스트"
    folder: "_posts"
    create: true
    # 이 줄이 있으면 제목만 써도 알아서 날짜가 붙어 저장됩니다.
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "제목", name: "title", widget: "string"}
      - {label: "날짜", name: "date", widget: "datetime"}
      - {label: "요약", name: "excerpt", widget: "text", required: false}
      - {label: "본문", name: "body", widget: "markdown"}
