backend:
  name: git-gateway
  branch: master

media_folder: "assets/images" # 이미지가 저장될 경로
public_folder: "/assets/images"

collections:
  - name: "posts"
    label: "포스트 등록"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "제목", name: "title", widget: "string" }
      - { label: "부제(요약)", name: "excerpt", widget: "string", required: false }
      - { label: "작성일", name: "date", widget: "datetime" }
      - { label: "대표 이미지(썸네일)", name: "header", widget: "object", fields: [
          { label: "이미지 선택", name: "teaser", widget: "image" }
        ]}
      - { label: "본문 내용", name: "body", widget: "markdown" }
