backend:
  name: github
  repo: "guccehchoi-commits/gucc_insight"
  branch: master

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "blog"
    label: "블로그 포스트"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "레이아웃", name: "layout", widget: "hidden", default: "single"}
      - {label: "제목", name: "title", widget: "string"}
      - {label: "날짜", name: "date", widget: "datetime"}
      - {label: "목록 썸네일 이미지", name: "header", widget: "object", fields: [
          {label: "이미지 선택", name: "teaser", widget: "image", required: false}
        ]}
      - {label: "요약", name: "excerpt", widget: "text", required: false}
      - {label: "본문", name: "body", widget: "markdown"}

  - name: "pages"
    label: "페이지 설정"
    files:
      - file: "/index.html"
        label: "메인 화면 관리"
        name: "index"
        fields:
          - {label: "메인 배너 이미지", name: "banner_image", widget: "image", required: false}
          - {label: "배너 높이(px)", name: "banner_height", widget: "number", default: 400}
          - {label: "최근글 제목 두께(100-900)", name: "post_title_weight", widget: "number", default: 300}
